Feature/add note details
MrXof/Note pull request #4
Opened 2024-03-29 16:30 UTC by MrXof

2024-03-29 16:30 UTC, MrXof commented
refactor

2024-03-29 16:55 UTC, O-Bielov requested changes

2024-03-29 16:55 UTC, O-Bielov commented on Note/Models/Note.swift
> +    var deadlineDate: Date?
відступ внизу

2024-03-29 16:55 UTC, O-Bielov commented on Note/Models/ObjectStore.swift
> +  func edit(index: Int, note: Note){
ми, знаючи id нотатки, не маємо потребу в індексі. тобто, нам треба буде приймати тільки нотатку, і потім самому шукати індекс елемента з таким id

2024-03-29 16:55 UTC, O-Bielov commented on Note/VC/ModalViewController.swift
>    @IBOutlet weak var completionOfAddition: UIButton!
погана назва. як її можна по іншому назвати?

2024-03-29 16:55 UTC, O-Bielov commented on Note/VC/ModalViewController.swift
> +      if statusData.isOn{
краще зробити так, щоб цей if рахував значення дати, і потім ти один раз звертався до objectStore

2024-03-29 16:55 UTC, O-Bielov commented on Note/VC/ModalViewController.swift
> +  @IBAction func takeDateAndTime(_ sender: Any) {
"взяти дату і час". ця функція робить щось інше. в тебе ця функція приміняє зміни в часу. тобто, apply

2024-03-29 16:55 UTC, O-Bielov commented on Note/VC/NoteInformationViewController.swift
> +class NoteInformationViewController: UIViewController{
відступи

2024-03-29 16:55 UTC, O-Bielov commented on Note/VC/NoteInformationViewController.swift
> +  var defaultValueIsDone: Bool = false
ну тепер зрозуміло чого саме це дефолте значення, але якщо це дефолтне значення, то воно ніколи не має змінюватись. тому що дефолтне значення - це одне значення. і в тебе значення змінної може або збігатись з стандартним(дефолтним) значенням, або не збігатись. тому дефолт тут взагалі не має бути присутнім
isDone - гарна назва

2024-03-29 16:55 UTC, O-Bielov commented on Note/VC/NoteInformationViewController.swift
> +        date.edit(index: indexRow, note: Note(id: count, name: textView.text, isDone: defaultValueIsDone, deadlineDate: dataValue))
цікавий факт. в тебе нотатка ніколи не змінює свій статус. тобто, в моделі Note є значення isDone, але по факту в моделі воно ніколи не змінюється

2024-03-29 16:55 UTC, O-Bielov commented on Note/Views/NoteTableViewCell.swift
> +                            , for: .normal)
тут в тебе якось дивно перенесено на новий рядок

2024-03-29 16:55 UTC, O-Bielov commented on Note/Views/NoteTableViewCell.swift
> +class NoteTableViewCell: UITableViewCell{
відступи

2024-03-29 16:55 UTC, O-Bielov commented on Note/Views/NoteTableViewCell.swift
> +  func displayNote(_ note: Note){
красивіше було б назвати цю функцію так:
display(note: Note)

2024-03-29 16:55 UTC, O-Bielov commented on Note/Views/NoteTableViewCell.swift
> +
зайвий відступ

2024-03-31 11:22 UTC, MrXof commented on Note/VC/ModalViewController.swift
> +      if statusData.isOn{
тут не погоджуюсь, бо в мене йде перевірка спершу на те чи взагалі текст не дорівнює nil
if textView.text != "Нотатки" && (textView.text != nil) != textView.text.isEmpty{  - ц екастильне вирішення валідіції, проте як є

2024-03-31 11:28 UTC, MrXof commented on Note/VC/NoteInformationViewController.swift
> +        date.edit(index: indexRow, note: Note(id: count, name: textView.text, isDone: defaultValueIsDone, deadlineDate: dataValue))
так , знаю, воно не змінює бо це фундамент на той випадок якщо потрібно буде покращювати додаток, поки що цей параметр не використовується, бо логіки по завершенню списку задач немає. Тому це бекграунд)

2024-03-31 11:28 UTC, O-Bielov commented on Note/VC/ModalViewController.swift
> +      if statusData.isOn{
перевірка на пустоту текста - це окреме обговорення. його взагалі краще замінити на guard)

я ж кажу за те, що ти в залежності від значення statusData.isOn або передаєш значення, або не передаєш його. тому я пропоную його так переписати:
```suggestion
let newDate: Date?
if statusData.isOn {
    newDate = dataValue
} else {
    newDate = nil
}
ObjectStore.shared.add(note: Note(id: count, name: textView.text, isDone: defaultValue, deadlineDate: newValue))
```

ми просто рахуємо це значення "за дужками", і потім його один раз вставляємо

2024-03-31 11:29 UTC, O-Bielov commented on Note/VC/ModalViewController.swift
>    var defaultValue: Bool = false
значення чого?

2024-03-31 11:32 UTC, MrXof commented on Note/VC/ModalViewController.swift
> +      if statusData.isOn{
тепер поняв за шо ти

2024-03-31 11:37 UTC, MrXof commented on Note/Views/NoteTableViewCell.swift
> +                            , for: .normal)
control + i  не допомогає, буду руцями робити)

2024-04-01 07:57 UTC, merged